# Generated by Django 4.2.7 on 2024-11-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadedresult',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='loadedresult',
            name='unit_code',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='complainant',
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(help_text='Enter a valid Username', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='system_user',
            name='username',
            field=models.CharField(help_text='Enter a valid Username', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='ArchivedComplaint',
        ),
        migrations.DeleteModel(
            name='LoadedResult',
        ),
    ]
