# Generated by Django 4.2.7 on 2024-11-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='response',
            name='response_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='ApprovedResponse',
        ),
    ]
