# Generated by Django 4.2.7 on 2024-11-06 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_loadedresult_reg_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='course_code',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_code',
            field=models.CharField(help_text='Please Enter Complaint Code', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='exam_date',
            field=models.DateField(help_text='Enter Main Exam Date, [dd, mm, yy]'),
        ),
        migrations.AlterField(
            model_name='response',
            name='cat',
            field=models.CharField(default='-', help_text='Enter Cat Mark or -', max_length=3),
        ),
        migrations.AlterField(
            model_name='response',
            name='exam',
            field=models.CharField(default='-', help_text='Enter Exam Mark or -', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.UniqueConstraint(fields=('unit_code', 'reg_no'), name='unique_complaint_per_unit_student'),
        ),
        migrations.AddConstraint(
            model_name='nominalroll',
            constraint=models.UniqueConstraint(fields=('unit_code', 'reg_no', 'academic_year'), name='unique_nominal_roll_per_unit_student_year'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('reg_no', 'unit_code'), name='unique_response_per_student_unit'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('unit_code', 'reg_no', 'academic_year'), name='unique_result_per_unit_student_year'),
        ),
        migrations.AddField(
            model_name='unitcourse',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.course'),
        ),
        migrations.AddField(
            model_name='unitcourse',
            name='unit_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.unit'),
        ),
    ]
