# Generated by Django 4.2.7 on 2024-11-09 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_response_alter_complaint_unit_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='response',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='unit_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.unit'),
        ),
        migrations.AlterField(
            model_name='response',
            name='complaint_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint'),
        ),
        migrations.AlterField(
            model_name='response',
            name='unit_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.unit'),
        ),
    ]
