# Generated by Django 4.2.7 on 2024-11-09 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_remove_complaint_response_alter_complaint_unit_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='unit_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.unit'),
        ),
    ]
