# Generated by Django 4.2.7 on 2024-11-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_alter_complaint_unit_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='complaint_code',
        ),
    ]
